backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/
public_folder: /img

collections:
  - name: "books"
    label: "Books"
    folder: "src/pages/books"
    create: true
    slug: "{{slug}}"
    fields:
    - {label: "Template Key", name: "templateKey", widget: hidden, default: "book-page"}
    - {label: "Title", name: "title", widget: string}
    - {label: "Book", name: "bookPDF", widget: file}

  - name: "pages"
    label: "Main Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "book-page"}
          - {label: Title, name: title, widget: string}