backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/assets
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Trunk"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "pdf-page"}
          - {label: Title, name: title, widget: string}
          - {label: PDF, name: pdf, widget: file}
  - name: "books"
    label: "Resources (Books)"
    folder: "src/pages/resources"
    create: true
    slug: "{{slug}}"
    fields:
    - {label: "Template Key", name: "templateKey", widget: hidden, default: "pdf-page"}
    - {label: "Title", name: "title", widget: string, required: true}
    - {label: PDF, name: pdf, widget: file, required: true}
  - name: "blog-posts"
    label: "Blog Posts"
    folder: "src/pages/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "post-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Series title", name: "seriesTitle", widget: "string" }
      - { label: "Series description", name: "seriesDescription", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - {
          label: "Attachments",
          name: "Attachments",
          widget: "list",
          summary: "{{fields.fileName}}",
          fields: [{label: "File name", name: fileName, widget: string}, {label: File, name: file, widget: file}]
        }